# Generated by Django 3.0.8 on 2020-08-03 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0004_auto_20200803_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='product_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price', to='shopping.Product'),
        ),
    ]
